export interface DefaultCategory {
  name: string;
  code: string;
  desc: string;
}

export const categoriesMap: Record<string, DefaultCategory[]> = {
  pharma: [
    { name: "Medicines", code: "MEDICINES", desc: "General medicines and drugs" },
    { name: "Cardiac Medicines", code: "CARDIAC", desc: "Cardiovascular drugs and treatments" },
    { name: "Diabetes Care", code: "DIABETES", desc: "Insulin and blood glucose control" },
    { name: "Respiratory Medicines", code: "RESPIRATORY", desc: "Asthma, COPD, inhalers and lung treatments" },
    { name: "Gastrointestinal Medicines", code: "GASTRO", desc: "Stomach, acid reflux, and digestive treatments" },
    { name: "Neurology Medicines", code: "NEURO", desc: "Brain, nerve, and psychiatric treatments" },
    { name: "Oncology Medicines", code: "ONCOLOGY", desc: "Cancer treatments and chemotherapy drugs" },
    { name: "Dermatology Medicines", code: "DERMA", desc: "Skin creams, ointments and dermatological drugs" },
    { name: "Ophthalmology Medicines", code: "OPHTHAL", desc: "Eye drops and eye treatments" },
    { name: "ENT Medicines", code: "ENT", desc: "Ear, nose, and throat treatments" },
    { name: "Orthopedic Medicines", code: "ORTHO", desc: "Bone, joint, and arthritis treatments" },
    { name: "Pediatric Medicines", code: "PEDIATRIC", desc: "Children medicines and liquid syrups" },
    { name: "Women's Health", code: "WOMEN", desc: "Hormones, contraceptives, and pregnancy support" },
    { name: "Men's Health", code: "MEN", desc: "Prostate, hair growth, and men support" },
    { name: "Hormonal Medicines", code: "HORMONAL", desc: "Thyroid, steroid, and endocrine drugs" },
    { name: "Pain Relief", code: "PAIN", desc: "Painkillers, muscle relaxants and gels" },
    { name: "Antibiotics", code: "ANTIBIOTICS", desc: "Bacterial infection treatments" },
    { name: "Antifungal Medicines", code: "ANTIFUNGAL", desc: "Fungal infection creams and pills" },
    { name: "Antiviral Medicines", code: "ANTIVIRAL", desc: "Viral infection treatments" },
    { name: "Allergy Medicines", code: "ALLERGY", desc: "Antihistamines and allergy relief" },
    { name: "Mental Health Medicines", code: "MENTAL", desc: "Antidepressants, anxiety and sleep drugs" },
    { name: "OTC (Over-the-Counter)", code: "OTC", desc: "General over-the-counter wellness" },
    { name: "Cold & Flu", code: "COLD_FLU", desc: "Cold and flu relief tablets" },
    { name: "Fever Medicines", code: "FEVER", desc: "Antipyretics and paracetamol" },
    { name: "Cough Syrups", code: "COUGH", desc: "Dry and wet cough syrups" },
    { name: "Digestive Care", code: "DIGESTIVE", desc: "Laxatives and digestive health" },
    { name: "Antacids", code: "ANTACIDS", desc: "Gas and acidity relief" },
    { name: "Pain Killers", code: "PAINKILLERS", desc: "Over-the-counter pain relief" },
    { name: "Sleep Aids", code: "SLEEP", desc: "Melatonin and mild sleep helpers" },
    { name: "Motion Sickness", code: "MOTION", desc: "Nausea and travel sickness" },
    { name: "Healthcare Products", code: "HEALTHCARE", desc: "General healthcare essentials" },
    { name: "Vitamins & Supplements", code: "VITAMINS", desc: "Multivitamins, calcium, immune boosters" },
    { name: "Protein Supplements", code: "PROTEIN", desc: "Whey protein, amino acids, diet supplements" },
    { name: "Nutrition Drinks", code: "NUTRITION", desc: "Ensure, Pediasure, health drinks" },
    { name: "Herbal Products", code: "HERBAL", desc: "Natural herbs and extracts" },
    { name: "Ayurvedic Medicines", code: "AYURVEDA", desc: "Traditional Indian ayurveda formulations" },
    { name: "Homeopathy", code: "HOMEOPATHY", desc: "Homeopathic pills and dilutions" },
    { name: "Immunity Boosters", code: "IMMUNITY", desc: "Chyawanprash, Vitamin C, Zinc" },
    { name: "Medical Devices", code: "DEVICES", desc: "Health monitoring equipment" },
    { name: "Blood Pressure Monitors", code: "BP_MONITOR", desc: "Sphygmomanometers and digital BP monitors" },
    { name: "Glucose Monitors", code: "GLUCOSE_MONITOR", desc: "Glucometers and test strips" },
    { name: "Nebulizers", code: "NEBULIZER", desc: "Inhaler machines and compressors" },
    { name: "Thermometers", code: "THERMOMETER", desc: "Digital and infrared thermometers" },
    { name: "Pulse Oximeters", code: "OXIMETER", desc: "SpO2 and pulse monitors" },
    { name: "Weighing Scales", code: "SCALES", desc: "Body and kitchen weighing scales" },
    { name: "Surgical & Clinical", code: "SURGICAL_CLINICAL", desc: "Professional clinical supplies" },
    { name: "Surgical Supplies", code: "SURGICAL_SUPPLIES", desc: "Scalpels, catheters, medical tape" },
    { name: "Wound Care", code: "WOUND", desc: "Antiseptic liquids, ointments and gauze" },
    { name: "Bandages", code: "BANDAGES", desc: "Crepe and adhesive bandages" },
    { name: "Cotton & Gauze", code: "COTTON", desc: "Absorbent cotton rolls and sterile gauze" },
    { name: "Syringes", code: "SYRINGES", desc: "Disposable needles and syringes" },
    { name: "Gloves", code: "GLOVES", desc: "Latex and nitrile examination gloves" },
    { name: "Masks", code: "MASKS", desc: "3-ply and N95 protective masks" },
    { name: "PPE Kits", code: "PPE", desc: "Personal protective equipment kits" },
    { name: "Catheters", code: "CATHETERS", desc: "Urinary catheters and tubes" },
    { name: "IV Sets", code: "IV_SETS", desc: "Intravenous infusion sets and cannulas" },
    { name: "Personal Care", code: "PERSONAL", desc: "General hygiene and body care" },
    { name: "Baby Care", code: "BABY", desc: "Baby powder, oil, wipes and rash creams" },
    { name: "Mother Care", code: "MOTHER", desc: "Maternity pads and stretch mark creams" },
    { name: "Oral Care", code: "ORAL", desc: "Toothbrushes, toothpaste, mouthwash" },
    { name: "Skin Care", code: "SKIN", desc: "Moisturizers, sunscreens, acne treatments" },
    { name: "Hair Care", code: "HAIR", desc: "Anti-dandruff shampoos and hair oils" },
    { name: "Sexual Wellness", code: "SEXUAL", desc: "Condoms, lubricants, wellness supplements" },
    { name: "Elderly Care", code: "ELDERLY", desc: "Adult diapers and walking support" }
  ],
  grocery: [
    { name: "Fresh Produce", code: "PRODUCE", desc: "Fresh organic items" },
    { name: "Vegetables", code: "VEGETABLES", desc: "Potatoes, onions, tomatoes and greens" },
    { name: "Fruits", code: "FRUITS", desc: "Apples, bananas, oranges, grapes" },
    { name: "Organic Vegetables", code: "ORGANIC_VEG", desc: "Certified chemical-free vegetables" },
    { name: "Herbs", code: "HERBS", desc: "Coriander, mint, basil, rosemary" },
    { name: "Exotic Fruits", code: "EXOTIC_FRUITS", desc: "Kiwi, dragon fruit, avocados" },
    { name: "Salad Items", code: "SALAD", desc: "Lettuce, cucumbers, cherry tomatoes" },
    { name: "Dairy", code: "DAIRY", desc: "Milk and dairy products" },
    { name: "Milk", code: "MILK", desc: "Pasteurized, full cream, toned milk" },
    { name: "Curd", code: "CURD", desc: "Yogurt, dahi, Greek yogurt" },
    { name: "Cheese", code: "CHEESE", desc: "Slices, blocks, mozzarella, cheddar" },
    { name: "Butter", code: "BUTTER", desc: "Salted and unsalted butter" },
    { name: "Paneer", code: "PANEER", desc: "Fresh cottage cheese blocks" },
    { name: "Eggs", code: "EGGS", desc: "Brown and white farm eggs" },
    { name: "Cream", code: "CREAM", desc: "Fresh cream and whipping cream" },
    { name: "Staples", code: "STAPLES", desc: "Daily essential groceries" },
    { name: "Rice", code: "RICE", desc: "Basmati, raw, and parboiled rice" },
    { name: "Wheat", code: "WHEAT", desc: "Whole wheat grains" },
    { name: "Flour", code: "FLOUR", desc: "Atta, maida, suji, besan" },
    { name: "Grains", code: "GRAINS", desc: "Oats, barley, corn, ragi" },
    { name: "Pulses", code: "PULSES", desc: "Moong, chana, urad, masoor dal" },
    { name: "Lentils", code: "LENTILS", desc: "Whole and split lentils" },
    { name: "Millets", code: "MILLETS", desc: "Bajra, jowar, foxtail millet" },
    { name: "Cooking Essentials", code: "COOKING_ESSENTIALS", desc: "Oils and condiments" },
    { name: "Edible Oils", code: "OILS", desc: "Mustard, sunflower, olive, coconut oil" },
    { name: "Ghee", code: "GHEE", desc: "Pure cow and buffalo desi ghee" },
    { name: "Spices", code: "SPICES", desc: "Turmeric, chilli powder, garam masala" },
    { name: "Salt", code: "SALT", desc: "Iodized and rock salt" },
    { name: "Sugar", code: "SUGAR", desc: "Refined sugar, brown sugar" },
    { name: "Jaggery", code: "JAGGERY", desc: "Gur blocks and powder" },
    { name: "Beverages", code: "BEVERAGES", desc: "Cold and hot drinks" },
    { name: "Tea", code: "TEA", desc: "Green, black, and masala tea bags/leaves" },
    { name: "Coffee", code: "COFFEE", desc: "Instant and filter coffee powder" },
    { name: "Soft Drinks", code: "SOFT_DRINKS", desc: "Colas, sodas, and fizzy drinks" },
    { name: "Juices", code: "JUICES", desc: "Fruit juices and nectars" },
    { name: "Energy Drinks", code: "ENERGY_DRINKS", desc: "Red Bull, Monster and sports drinks" },
    { name: "Health Drinks", code: "HEALTH_DRINKS", desc: "Horlicks, Bournvita, protein shakes" },
    { name: "Water", code: "WATER", desc: "Mineral and packaged drinking water" },
    { name: "Bakery", code: "BAKERY", desc: "Freshly baked items" },
    { name: "Bread", code: "BREAD", desc: "White, brown, and multigrain sandwich bread" },
    { name: "Cakes", code: "CAKES", desc: "Pastries, muffins, sliced cakes" },
    { name: "Biscuits", code: "BISCUITS", desc: "Sweet, salty and digestive biscuits" },
    { name: "Cookies", code: "COOKIES", desc: "Chocolate chip and butter cookies" },
    { name: "Buns", code: "BUNS", desc: "Burger buns, pav, sweet buns" },
    { name: "Frozen Foods", code: "FROZEN", desc: "Packaged frozen goods" },
    { name: "Frozen Vegetables", code: "FROZEN_VEG", desc: "Frozen peas, sweet corn, mixed vegetables" },
    { name: "Frozen Snacks", code: "FROZEN_SNACKS", desc: "Fries, nuggets, samosas" },
    { name: "Ice Cream", code: "ICE_CREAM", desc: "Tubs, cones, and family packs" },
    { name: "Frozen Meat", code: "FROZEN_MEAT", desc: "Frozen chicken, fish, sausage" },
    { name: "Snacks", code: "SNACKS", desc: "Snack foods" },
    { name: "Chips", code: "CHIPS", desc: "Potato chips, nachos, banana chips" },
    { name: "Namkeen", code: "NAMKEEN", desc: "Bhujia, sev, mixture, peanuts" },
    { name: "Chocolates", code: "CHOCOLATES", desc: "Bars, candies, dark chocolates" },
    { name: "Dry Fruits", code: "DRY_FRUITS", desc: "Almonds, cashews, raisins, pistachios" },
    { name: "Nuts", code: "NUTS", desc: "Walnuts, peanuts, mixed nuts" },
    { name: "Popcorn", code: "POPCORN", desc: "Microwave and ready-to-eat popcorn" },
    { name: "Household", code: "HOUSEHOLD", desc: "Home care essentials" },
    { name: "Cleaning Supplies", code: "CLEANING", desc: "Floor, toilet and glass cleaners" },
    { name: "Detergents", code: "DETERGENTS", desc: "Washing powder and liquid detergents" },
    { name: "Dishwashing", code: "DISHWASHING", desc: "Bars, liquids, and scrubs" },
    { name: "Air Fresheners", code: "FRESHENERS", desc: "Room sprays, pocket fresheners" },
    { name: "Garbage Bags", code: "GARBAGE_BAGS", desc: "Biodegradable trash bags" },
    { name: "Personal Care", code: "PERSONAL_CARE", desc: "Self hygiene products" },
    { name: "Shampoo", code: "SHAMPOO", desc: "Hair cleansers and conditioners" },
    { name: "Soap", code: "SOAP", desc: "Bathing bars and liquid handwash" },
    { name: "Toothpaste", code: "TOOTHPASTE", desc: "Fluoride, herbal and whitening toothpaste" },
    { name: "Face Wash", code: "FACE_WASH", desc: "Cleansing gels and scrubs" },
    { name: "Cosmetics", code: "COSMETICS", desc: "Lipbalms, creams, makeup" },
    { name: "Baby Products", code: "BABY_PRODUCTS", desc: "Infant care items" },
    { name: "Baby Food", code: "BABY_FOOD", desc: "Formula milk, cereals, baby puree" },
    { name: "Diapers", code: "DIAPERS", desc: "Baby pant diapers, tape diapers" },
    { name: "Baby Wipes", code: "BABY_WIPES", desc: "Fragrance-free sensitive baby wipes" },
    { name: "Baby Lotion", code: "BABY_LOTION", desc: "Baby moisturizing creams and powders" },
    { name: "Pet Care", code: "PET_CARE", desc: "Animal food and accessories" },
    { name: "Dog Food", code: "DOG_FOOD", desc: "Dry kibble and wet canned dog food" },
    { name: "Cat Food", code: "CAT_FOOD", desc: "Wet and dry cat food pouches" },
    { name: "Pet Accessories", code: "PET_ACCESSORIES", desc: "Collars, leashes, toys, shampoo" }
  ],
  auto: [
    { name: "Engine", code: "ENGINE_SYS", desc: "Complete engine assemblies and blocks" },
    { name: "Engine Parts", code: "ENGINE_PARTS", desc: "Valves, camshafts, pistons, rings" },
    { name: "Pistons", code: "PISTONS", desc: "Engine cylinder pistons" },
    { name: "Crankshaft", code: "CRANKSHAFT", desc: "Engine main crankshafts" },
    { name: "Camshaft", code: "CAMSHAFT", desc: "Engine camshafts" },
    { name: "Timing Kit", code: "TIMING_KIT", desc: "Timing belts, tensioners, chains" },
    { name: "Gaskets", code: "GASKETS", desc: "Cylinder head and oil pan gaskets" },
    { name: "Electrical", code: "ELECTRICAL_SYS", desc: "Automotive electrical system parts" },
    { name: "Battery", code: "BATTERY", desc: "12V lead-acid and AGM car batteries" },
    { name: "Alternator", code: "ALTERNATOR", desc: "Charging system alternators" },
    { name: "Starter Motor", code: "STARTER", desc: "Ignition starter motors" },
    { name: "Wiring Harness", code: "WIRING", desc: "Connectors, terminals, main wire harnesses" },
    { name: "Relays", code: "RELAYS", desc: "Fuses and electrical relays" },
    { name: "Sensors", code: "SENSORS", desc: "O2, MAP, MAF, and temperature sensors" },
    { name: "ECU", code: "ECU", desc: "Engine control units and modules" },
    { name: "Fuel System", code: "FUEL_SYSTEM", desc: "Fuel tank and delivery parts" },
    { name: "Fuel Pump", code: "FUEL_PUMP", desc: "Electric and mechanical fuel pumps" },
    { name: "Fuel Injector", code: "FUEL_INJECTOR", desc: "Fuel injection nozzles" },
    { name: "Fuel Filter", code: "FUEL_FILTER", desc: "In-line fuel filters" },
    { name: "Carburetor", code: "CARBURETOR", desc: "Classic air-fuel mixing carburetors" },
    { name: "Cooling System", code: "COOLING_SYS", desc: "Engine cooling and thermostat" },
    { name: "Radiator", code: "RADIATOR", desc: "Aluminum and plastic radiator cores" },
    { name: "Coolant", code: "COOLANT", desc: "Antifreeze liquids" },
    { name: "Water Pump", code: "WATER_PUMP", desc: "Coolant circulation water pumps" },
    { name: "Thermostat", code: "THERMOSTAT", desc: "Temperature control thermostats" },
    { name: "Cooling Fan", code: "COOLING_FAN", desc: "Electric radiator cooling fans" },
    { name: "Suspension", code: "SUSPENSION_SYS", desc: "Shocks, struts and springs" },
    { name: "Shock Absorbers", code: "SHOCKS", desc: "Gas and oil shock absorbers" },
    { name: "Springs", code: "SPRINGS", desc: "Coil and leaf suspension springs" },
    { name: "Control Arms", code: "CONTROL_ARMS", desc: "Suspension wishbones and arms" },
    { name: "Bushes", code: "BUSHES", desc: "Polyurethane suspension bushes" },
    { name: "Ball Joints", code: "BALL_JOINTS", desc: "Steering knuckle ball joints" },
    { name: "Steering", code: "STEERING_SYS", desc: "Rack, pinion and power steering" },
    { name: "Steering Rack", code: "STEERING_RACK", desc: "Manual and power steering racks" },
    { name: "Power Steering Pump", code: "STEERING_PUMP", desc: "Hydraulic power steering pumps" },
    { name: "Tie Rods", code: "TIE_RODS", desc: "Inner and outer tie rod ends" },
    { name: "Steering Column", code: "STEERING_COLUMN", desc: "Steering shafts and columns" },
    { name: "Brake System", code: "BRAKE_SYS", desc: "Braking calipers, boosters and lines" },
    { name: "Brake Pads", code: "BRAKE_PADS", desc: "Ceramic and semi-metallic brake pads" },
    { name: "Brake Shoes", code: "BRAKE_SHOES", desc: "Rear drum brake shoe linings" },
    { name: "Brake Disc", code: "BRAKE_DISC", desc: "Rotors and ventilated brake discs" },
    { name: "Brake Drum", code: "BRAKE_DRUM", desc: "Cast iron rear brake drums" },
    { name: "Brake Fluid", code: "BRAKE_FLUID", desc: "DOT 3, DOT 4, and DOT 5.1 fluids" },
    { name: "Master Cylinder", code: "BRAKE_MASTER", desc: "Brake master pressure cylinders" },
    { name: "Transmission", code: "TRANSMISSION_SYS", desc: "Clutches, shafts and gearboxes" },
    { name: "Clutch Kit", code: "CLUTCH_KIT", desc: "Clutch plate, cover, and release bearing" },
    { name: "Gearbox", code: "GEARBOX", desc: "Manual and automatic gear assemblies" },
    { name: "Flywheel", code: "FLYWHEEL", desc: "Dual mass and solid flywheels" },
    { name: "Differential", code: "DIFFERENTIAL", desc: "Rear axle differentials and gears" },
    { name: "Exhaust", code: "EXHAUST_SYS", desc: "Manifolds, pipes and silencers" },
    { name: "Exhaust Pipe", code: "EXHAUST_PIPE", desc: "Exhaust extension pipes" },
    { name: "Silencer", code: "SILENCER", desc: "Mufflers and decibel reducers" },
    { name: "Catalytic Converter", code: "CATALYTIC_CONVERTER", desc: "Emissions control converters" },
    { name: "Muffler", code: "MUFFLER", desc: "Exhaust muffler silencers" },
    { name: "Wheels", code: "WHEELS_SYS", desc: "Rims, tyres and hub parts" },
    { name: "Tyres", code: "TYRES", desc: "Car, SUV, and truck rubber tyres" },
    { name: "Alloy Wheels", code: "ALLOY_WHEELS", desc: "Premium aluminum alloy rims" },
    { name: "Steel Wheels", code: "STEEL_WHEELS", desc: "Standard heavy duty steel rims" },
    { name: "Wheel Bearings", code: "BEARINGS", desc: "Hub assembly wheel bearings" },
    { name: "Body & Exterior", code: "BODY_EXTERIOR", desc: "Doors, hoods, fenders, mirrors" },
    { name: "Doors", code: "DOORS", desc: "Side doors and tailgate panels" },
    { name: "Mirrors", code: "MIRRORS", desc: "Side wing mirrors and rearview mirrors" },
    { name: "Headlights", code: "HEADLIGHTS", desc: "Halogen, LED, and Xenon headlamps" },
    { name: "Tail Lights", code: "TAIL_LIGHTS", desc: "Rear brake and indicator lamps" },
    { name: "Bumpers", code: "BUMPERS", desc: "Front and rear bumper covers" },
    { name: "Bonnet", code: "BONNET", desc: "Engine hood panels" },
    { name: "Fender", code: "FENDER", desc: "Wheel arch fender panels" },
    { name: "Windshield", code: "WINDSHIELD", desc: "Front laminated windshield glass" },
    { name: "Wipers", code: "WIPERS", desc: "Wiper arms and silicone blades" },
    { name: "Interior", code: "INTERIOR_SYS", desc: "Seats, mats, dashboards" },
    { name: "Seat Covers", code: "SEAT_COVERS", desc: "Leather and fabric seat cover sets" },
    { name: "Floor Mats", code: "FLOOR_MATS", desc: "Rubber and carpet floor protectors" },
    { name: "Dashboard Accessories", code: "DASH_ACC", desc: "Phone mounts, fragrance, trims" },
    { name: "Steering Covers", code: "STEERING_COVERS", desc: "Leather grip steering wheel wraps" },
    { name: "Infotainment Systems", code: "INFOTAINMENT", desc: "Touchscreen car stereos and speakers" },
    { name: "Accessories", code: "ACCESSORIES", desc: "Add-on custom automotive accessories" },
    { name: "Car Care Products", code: "CAR_CARE", desc: "Car wash, waxes, polishes, shampoos" },
    { name: "Cleaning Kits", code: "CLEANING_KITS", desc: "Microfiber cloths, sponges, sprayers" },
    { name: "Mobile Holders", code: "MOBILE_HOLDERS", desc: "Magnetic and suction dash mounts" },
    { name: "Roof Carriers", code: "ROOF_CARRIERS", desc: "Luggage roof racks and crossbars" },
    { name: "Dash Cameras", code: "DASH_CAMS", desc: "Front and rear recording dash cameras" },
    { name: "Reverse Cameras", code: "REVERSE_CAMS", desc: "Parking assist rearview backup cameras" },
    { name: "Parking Sensors", code: "PARKING_SENSORS", desc: "Ultrasonic distance parking sensors" },
    { name: "Lubricants", code: "LUBRICANTS", desc: "Friction reduction oils and grease" },
    { name: "Engine Oil", code: "ENGINE_OIL", desc: "5W-30, 10W-40 synthetic motor oils" },
    { name: "Gear Oil", code: "GEAR_OIL", desc: "Differential and manual transmission fluid" },
    { name: "Brake Oil", code: "BRAKE_OIL", desc: "Hydraulic braking fluid" },
    { name: "Grease", code: "GREASE", desc: "High temperature wheel bearing grease" },
    { name: "Tools", code: "TOOLS_SYS", desc: "Service jacks, diagnostic scanners, wrenches" },
    { name: "Tool Kits", code: "TOOL_KITS", desc: "Socket wrenches, screwdrivers, spanners" },
    { name: "Hydraulic Jack", code: "JACK", desc: "Bottle and trolley hydraulic car jacks" },
    { name: "Air Compressor", code: "COMPRESSOR", desc: "12V portable tire inflator pumps" },
    { name: "Diagnostic Scanner", code: "SCANNER", desc: "OBD2 engine code reader scanners" }
  ]
};
